language: python
sudo: required
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
before_install:
- wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
- unzip terraform_0.11.13_linux_amd64.zip
install:
# Install charm crypto framework and dependencies
- sudo chmod +x install.sh && ./install.sh
# Install other requirements
- pip install -r requirements.txt
- pip install .
- ./terraform init terraform-infra
script:
- pytest -k 'not boundaries'
- ./terraform validate terraform-infra