#!/usr/bin/env python
"""
Usage: cryptocracy setup [options]
       cryptocracy generate keypair [--public-key-file=<pku>] [--secret-key-file=<sku>] [options]
       cryptocracy register <email_address> [--public-key-file=<pku>] [options]
       cryptocracy add user <email_address> <attributes_json_array> [options]
       cryptocracy list (user|file) [options]
       cryptocracy revoke user <email_address> [options]
       cryptocracy encrypt <input_file> <policy_expression> <output_file> [options]
       cryptocracy decrypt <file> [options]
       cryptocracy upload <source_url> [<dest_key>] [options]
       cryptocracy download <url> <user_id> [options]

Options:
  --params=FILE                  Path to the scheme public parameters file to use for CLI commands. [default: $HOME/.cryptocracy/params]
  --public-key-file=<pku>        Destination path for user public key generation [default: $HOME/.cryptocracy/user.pub]
  --secret-key-file=<sku>        Destination path for user secret key generation [default: $HOME/.cryptocracy/user.key]
  --email-address=ADDRESS        Identity of the caller for upload download commands.
  -v, --verbose                  Show debug information.
  -h --help                      Show this screen.
  --version                      Show version.

"""
__version__ = '0.1.0'

import os
import traceback

import requests
from docopt import docopt

from src.boundaries.object_store import AwsObjectStore
from src.boundaries.proxy_key_store import AwsProxyKeyStore
from src.model.abe_scheme import CharmHybridABE
from src.model.result import RESULT
from src.use_cases.add_user import AddUserUseCase, AddUserRequest
from src.use_cases.download_file import DownloadFileUseCase, DownloadFileRequest
from src.use_cases.encrypt_file import EncryptFileUseCase, EncryptFileRequest
from src.use_cases.generate_key_pair import GenerateKeyPairUseCase, GenerateKeyPairRequest
from src.use_cases.list_users import ListUsersUseCase, ListUsersRequest
from src.use_cases.register_user import RegisterUserUseCase, RegisterUserRequest
from src.use_cases.revoke_user import RevokeUserUseCase, RevokeUserRequest
from src.use_cases.setup import SetupUseCase, SetupRequest
from src.use_cases.upload_file import UploadFileUseCase, UploadFileRequest


def main():
    try:
        (setup,
         generate_key_pair,
         register_user,
         add_user,
         revoke_user,
         list_users,
         download_file,
         encrypt_file,
         upload_file) = init_use_cases()

        cryptocracy_home = create_cryptocracy_home()

        arguments = docopt(__doc__, version=__version__)
        if arguments['--verbose']:
            print(arguments)
        user_id = arguments['<email_address>']
        response = "Coming soon..!"
        if arguments['setup']:
            response = setup.run(SetupRequest())
            save_setup(cryptocracy_home, response)
        if arguments['generate'] and arguments['keypair']:
            response = generate_key_pair.run(GenerateKeyPairRequest(params=load(arguments['--params']),
                                                                    public_key_file=arguments['--public-key-file'],
                                                                    secret_key_file=arguments['--secret-key-file']))
        if arguments['register']:
            response = register_user.run(RegisterUserRequest(user_id=user_id,
                                                  pku_b64=load(arguments['--public-key-file'])))
            if arguments['add']:
                response = add_user.run(AddUserRequest(user_id=user_id, attributes=arguments['<attributes_json_array>']))
            elif arguments['revoke']:
                response = revoke_user.run(RevokeUserRequest(user_id=user_id))
            elif arguments['list']:
                response = list_users.run(ListUsersRequest())
        if arguments['upload']:
            response = upload_file.run(UploadFileRequest(arguments['<source_url>']))
        if arguments['download']:
            response = download_file.run(DownloadFileRequest(user_id=arguments['<user_id>'],
                                                             request_url=arguments['<url>']))
        if arguments['encrypt']:
            response = encrypt_file.run(
                EncryptFileRequest(input_file=arguments['<input_file>'],
                                   policy_expression=arguments['<policy_expression>'],
                                   output_file=arguments['<output_file>'],
                                   params=load(arguments['--params'])))

        print(response)
    except Exception as err:
        print(err)
        traceback.print_tb(err.__traceback__)


def init_use_cases():
    proxy_key_store = AwsProxyKeyStore(os.getenv('CRYPTOCRACY_PROXY_KEY_STORE_TABLE_NAME'))
    abe_scheme = CharmHybridABE()
    setup = SetupUseCase(abe_scheme)
    generate_key_pair = GenerateKeyPairUseCase(abe_scheme)
    register_user = RegisterUserUseCase(requests, server_address="localhost:5000")
    add_user = AddUserUseCase(requests, abe_scheme, proxy_key_store)
    revoke_user = RevokeUserUseCase(proxy_key_store)
    list_users = ListUsersUseCase(proxy_key_store)

    object_store = AwsObjectStore(os.getenv('CRYPTOCRACY_OBJECT_STORE_BUCKET_NAME'))
    object_cache = AwsObjectStore(os.getenv('CRYPTOCRACY_OBJECT_CACHE_BUCKET_NAME'))
    upload_file = UploadFileUseCase(object_store)
    download_file = DownloadFileUseCase(proxy_key_store, None, object_store, object_cache, abe_scheme=abe_scheme)

    encrypt_file = EncryptFileUseCase(abe_scheme)
    return (setup,
            generate_key_pair,
            register_user,
            add_user,
            revoke_user,
            list_users,
            download_file,
            encrypt_file,
            upload_file)


def save_setup(cryptocracy_home, response):
    if response['result'] == RESULT.SUCCESS:
        with open(os.open(os.path.join(cryptocracy_home, 'msk'), os.O_CREAT | os.O_WRONLY, 0o600), 'wb') as f:
            f.write(response['msk'])
        with open(os.open(os.path.join(cryptocracy_home, 'params'), os.O_CREAT | os.O_WRONLY, 0o644), 'wb') as f:
            f.write(response['params'])


def create_cryptocracy_home():
    home = os.path.expanduser("~")
    cryptocracy_home = os.path.join(home, '.cryptocracy')
    os.makedirs(cryptocracy_home, mode=0o700, exist_ok=True)
    return cryptocracy_home


def load(config_file):
    """
    :param config_file: a Cryptocracy param file holding a single value.
    :return: the file contents as (base64-encoded) bytes
    """
    with open(os.path.expandvars(config_file), 'rb') as c:
        return c.read()


if __name__ == '__main__':
    main()
